GET http://localhost:3000/api/media
Content-Type: application/json

###
GET http://localhost:3000/api/media/9589
Content-Type: application/json

###
POST http://localhost:3000/api/media
Content-Type: application/json

{
  "filename": "60ac.jpg",
  "title": "New image",
  "description": "The description of the new image",
  "user_id": 305,
  "media_type": "image/jpeg"
}

###
PUT http://localhost:3000/api/media/9590
Content-Type: application/json

{
  "title": "Basement modified",
  "description": "Some new description"
}

###
DELETE http://localhost:3000/api/media/9590
Content-Type: application/json

###
GET http://localhost:3000/api/user
Content-Type: application/jsons

###
GET http://localhost:3000/api/user/305
Content-Type: application/json

###
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword",
  "email": ""
}

###
PUT http://localhost:3000/api/user/305
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword",
  "email": ""
}

###
DELETE http://localhost:3000/api/user/305
Content-Type: application/json