GET http://localhost:3000/api/media
Content-Type: application/json

###
GET http://localhost:3000/api/media/9589
Content-Type: application/json

###
POST http://localhost:3000/api/media
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user_id"

1

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

New image

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

The description of the new image

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
PUT http://localhost:3000/api/media/1
Content-Type: application/json

{
  "title": "Basement modified",
  "description": "Some new description"
}

###
DELETE http://localhost:3000/api/media/9590
Content-Type: application/json

###
GET http://localhost:3000/api/user
Content-Type: application/jsons

###
GET http://localhost:3000/api/user/305
Content-Type: application/json

###
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword",
  "email": ""
}

###
PUT http://localhost:3000/api/user/305
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword",
  "email": ""
}

###
DELETE http://localhost:3000/api/user/305
Content-Type: application/json

### Post login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "newuser",
  "password": "newpassword"
}

### Get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6Im5ld3VzZXIiLCJwYXNzd29yZCI6Im5ld3Bhc3N3b3JkIiwiZW1haWwiOiIiLCJ1c2VyX2xldmVsX2lkIjoxLCJjcmVhdGVkX2F0IjoiMjAyMy0xMS0xNVQwNjozMToyMi4wMDBaIiwiaWF0IjoxNzAwNjQxMTg5LCJleHAiOjE3MDA3Mjc1ODl9.lnArhrna0TldptnrthMqqkRANjXJTiEuvH1HhRh09Qs